# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c1ae4da031262737ac8291cc435dcbb64f48e77130ff69f89c2269b852466431e5b0476cace47ec6e51af23b35310001f9d0fa20689a9a41c729e53ca29b329

test:
  secret_key_base: bc15c77d331235fd94ac0b9c9da092507221e1a100da43a0bda677180d57a450bb0d3111f3355524e77881fea08c32998e149a32ff68607e8e03f54b4ec39d95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
